/* ============================================================
   RIO POLICY REGISTER, deep data
   ------------------------------------------------------------
   Each entry is a dossier, not a summary. Fields:
     org       display name
     full      the journals/imprints it governs
     cat       standards | publisher | journal | funder
     verdict   plain-language headline ruling
     chips     [{t: label, s: ok|warn|stop}]
     writing   what is permitted + WHERE the disclosure goes
     images    the strictest and most divergent axis
     review    peer-review rules
     screening what the publisher actually runs against you
     forYou    one practical line for an NCBS researcher
     covers    titles this governs (also feeds search)
   To connect a backend: replace this array with a fetch of the
   same shape. Nothing in register.js needs to change.
   ============================================================ */

const REGISTER_UPDATED = "August 2026";

/* ------------------------------------------------------------
   JOURNAL INDEX · maps journal titles to the register entry that
   governs them. Feeds the search suggestions. The `o` value must
   match an entry's `org` field exactly.
   ------------------------------------------------------------ */
const JOURNAL_INDEX = [
  {j:"Nature", o:"Springer Nature"},
  {j:"Nature Methods", o:"Springer Nature"},
  {j:"Nature Communications", o:"Springer Nature", d:"August 2026", u:"https://www.nature.com/nature-portfolio/editorial-policies/ai",
   v:"Nature Portfolio journals share a single set of editorial policies, so the Springer Nature entry below is the journal&rsquo;s policy; no journal-specific additions."},
  {j:"Nature Cell Biology", o:"Springer Nature"},
  {j:"Nature Neuroscience", o:"Springer Nature"},
  {j:"Nature Genetics", o:"Springer Nature"},
  {j:"Nature Structural &amp; Molecular Biology", o:"Springer Nature"},
  {j:"Nature Chemical Biology", o:"Springer Nature"},
  {j:"Nature Ecology &amp; Evolution", o:"Springer Nature"},
  {j:"Nature Biotechnology", o:"Springer Nature"},
  {j:"Nature Medicine", o:"Springer Nature"},
  {j:"Nature Immunology", o:"Springer Nature"},
  {j:"Nature Microbiology", o:"Springer Nature"},
  {j:"Nature Plants", o:"Springer Nature"},
  {j:"Nature Metabolism", o:"Springer Nature"},
  {j:"Nature Aging", o:"Springer Nature"},
  {j:"Nature Physics", o:"Springer Nature"},
  {j:"Nature Chemistry", o:"Springer Nature"},
  {j:"Scientific Reports", o:"Springer Nature"},
  {j:"Communications Biology", o:"Springer Nature"},
  {j:"BMC Biology", o:"Springer Nature"},
  {j:"BMC Genomics", o:"Springer Nature"},
  {j:"BMC Bioinformatics", o:"Springer Nature"},
  {j:"Journal of Biosciences", o:"Springer Nature", d:"August 2026", u:"https://link.springer.com/journal/12038/submission-guidelines",
   v:"The submission guidelines add no AI-specific rules of their own and point to Springer Nature&rsquo;s shared editorial policies, so the platform policy governs: document LLM use in Methods, copy editing exempt, no generative AI images."},
  {j:"Journal of Genetics", o:"Springer Nature"},
  {j:"Chromosoma", o:"Springer Nature"},
  {j:"Cell and Tissue Research", o:"Springer Nature"},
  {j:"Oecologia", o:"Springer Nature"},
  {j:"Behavioral Ecology and Sociobiology", o:"Springer Nature"},
  {j:"Cell", o:"Cell Press"},
  {j:"Molecular Cell", o:"Cell Press"},
  {j:"Neuron", o:"Cell Press"},
  {j:"Immunity", o:"Cell Press"},
  {j:"Developmental Cell", o:"Cell Press"},
  {j:"Current Biology", o:"Cell Press"},
  {j:"Cell Reports", o:"Cell Press"},
  {j:"Cell Systems", o:"Cell Press"},
  {j:"Cell Metabolism", o:"Cell Press"},
  {j:"Cancer Cell", o:"Cell Press"},
  {j:"Cell Stem Cell", o:"Cell Press"},
  {j:"Cell Host &amp; Microbe", o:"Cell Press"},
  {j:"Structure", o:"Cell Press"},
  {j:"Biophysical Journal", o:"Cell Press", d:"August 2026", u:"https://www.cell.com/biophysj/authors",
   v:"Uses the standard Elsevier disclosure rather than extra Cell Press restrictions on writing: AI only to improve readability and language, declared in a section titled &ldquo;Declaration of generative AI and AI-assisted technologies in the writing process&rdquo; placed before the references, with the template sentence given on the journal page. Grammar and spelling tools need no statement."},
  {j:"iScience", o:"Cell Press"},
  {j:"Heliyon", o:"Cell Press"},
  {j:"STAR Protocols", o:"Cell Press"},
  {j:"Trends in Cell Biology", o:"Cell Press"},
  {j:"Trends in Neurosciences", o:"Cell Press"},
  {j:"Trends in Ecology &amp; Evolution", o:"Cell Press"},
  {j:"Trends in Biochemical Sciences", o:"Cell Press"},
  {j:"Molecular Plant", o:"Cell Press"},
  {j:"Patterns", o:"Cell Press"},
  {j:"Journal of Molecular Biology", o:"Elsevier"},
  {j:"Developmental Biology", o:"Elsevier"},
  {j:"Gene", o:"Elsevier"},
  {j:"Neuroscience", o:"Elsevier"},
  {j:"Brain Research", o:"Elsevier"},
  {j:"Current Opinion in Cell Biology", o:"Elsevier"},
  {j:"Current Opinion in Neurobiology", o:"Elsevier"},
  {j:"Current Opinion in Structural Biology", o:"Elsevier"},
  {j:"Journal of Theoretical Biology", o:"Elsevier"},
  {j:"Animal Behaviour", o:"Elsevier"},
  {j:"Biochimica et Biophysica Acta (BBA)", o:"Elsevier"},
  {j:"Journal of Structural Biology", o:"Elsevier"},
  {j:"Virology", o:"Elsevier"},
  {j:"NeuroImage", o:"Elsevier"},
  {j:"Cognition", o:"Elsevier"},
  {j:"The Lancet", o:"The Lancet"},
  {j:"The Lancet Infectious Diseases", o:"The Lancet"},
  {j:"The Lancet Neurology", o:"The Lancet"},
  {j:"eBioMedicine", o:"The Lancet"},
  {j:"Human Brain Mapping", o:"Wiley"},
  {j:"Journal of Extracellular Vesicles", o:"Wiley"},
  {j:"BioEssays", o:"Wiley"},
  {j:"Developmental Dynamics", o:"Wiley"},
  {j:"Glia", o:"Wiley"},
  {j:"Hippocampus", o:"Wiley"},
  {j:"Journal of Comparative Neurology", o:"Wiley"},
  {j:"Traffic", o:"Wiley"},
  {j:"Protein Science", o:"Wiley"},
  {j:"Proteins", o:"Wiley", d:"August 2026", u:"https://onlinelibrary.wiley.com/page/journal/10970134/homepage/forauthors.html",
   v:"The journal&rsquo;s own author guidelines (updated July 2025) contain no AI-specific section, so Wiley&rsquo;s platform policy governs. The journal is a COPE member and screens text with iThenticate."},
  {j:"Journal of Neurochemistry", o:"Wiley"},
  {j:"Molecular Ecology", o:"Wiley"},
  {j:"Ecology Letters", o:"Wiley"},
  {j:"The Journal of Physiology", o:"Wiley", d:"August 2026", u:"https://jp.msubmit.net/cgi-bin/main.plex?form_type=display_requirements",
   v:"Has its own mandatory Generative AI Statement in the Additional Information section: name, model and version of every tool plus exact purpose and method of use, and if no generative AI was used the manuscript must say so explicitly. Peer reviewers are prohibited from using generative AI. Spelling and grammar checkers fall outside the policy."},
  {j:"Molecular Microbiology", o:"Wiley", d:"August 2026", u:"https://onlinelibrary.wiley.com/page/journal/13652958/homepage/forauthors.html",
   v:"Stricter than the Wiley platform: text, figures or images created by generative AI tools cannot be used in papers in this journal without explicit permission from the editor. AI content is discouraged outside formal research design or methods, and any use requires naming the model or tool. Review articles must declare any generative-AI use in preparation or editing."},
  {j:"Autophagy", o:"Taylor &amp; Francis"},
  {j:"Cell Cycle", o:"Taylor &amp; Francis"},
  {j:"Nucleus", o:"Taylor &amp; Francis"},
  {j:"Fly", o:"Taylor &amp; Francis"},
  {j:"RNA Biology", o:"Taylor &amp; Francis"},
  {j:"mAbs", o:"Taylor &amp; Francis"},
  {j:"Small GTPases", o:"Taylor &amp; Francis"},
  {j:"Virulence", o:"Taylor &amp; Francis"},
  {j:"Nucleic Acids Research", o:"Oxford University Press"},
  {j:"Bioinformatics", o:"Oxford University Press"},
  {j:"Briefings in Bioinformatics", o:"Oxford University Press"},
  {j:"Molecular Biology and Evolution", o:"Oxford University Press"},
  {j:"Genome Biology and Evolution", o:"Oxford University Press"},
  {j:"GigaScience", o:"Oxford University Press"},
  {j:"Genetics", o:"Oxford University Press"},
  {j:"G3: Genes, Genomes, Genetics", o:"Oxford University Press"},
  {j:"Brain", o:"Oxford University Press"},
  {j:"Cerebral Cortex", o:"Oxford University Press"},
  {j:"Chemical Senses", o:"Oxford University Press"},
  {j:"Behavioral Ecology", o:"Oxford University Press"},
  {j:"Human Molecular Genetics", o:"Oxford University Press"},
  {j:"Glycobiology", o:"Oxford University Press"},
  {j:"FEMS Microbiology Letters", o:"Oxford University Press"},
  {j:"FEMS Microbiology Reviews", o:"Oxford University Press"},
  {j:"Quarterly Reviews of Biophysics", o:"Cambridge University Press"},
  {j:"Parasitology", o:"Cambridge University Press"},
  {j:"Journal of Fluid Mechanics", o:"Cambridge University Press"},
  {j:"International Journal of Molecular Sciences", o:"MDPI"},
  {j:"Cells", o:"MDPI"},
  {j:"Biomolecules", o:"MDPI"},
  {j:"Viruses", o:"MDPI"},
  {j:"Microorganisms", o:"MDPI"},
  {j:"Insects", o:"MDPI"},
  {j:"Genes", o:"MDPI"},
  {j:"Frontiers in Neuroscience", o:"Frontiers"},
  {j:"Frontiers in Immunology", o:"Frontiers"},
  {j:"Frontiers in Cell and Developmental Biology", o:"Frontiers"},
  {j:"Frontiers in Microbiology", o:"Frontiers"},
  {j:"Frontiers in Neural Circuits", o:"Frontiers"},
  {j:"Frontiers in Molecular Neuroscience", o:"Frontiers"},
  {j:"Science", o:"Science · AAAS"},
  {j:"Science Advances", o:"Science · AAAS"},
  {j:"Science Immunology", o:"Science · AAAS"},
  {j:"Science Signaling", o:"Science · AAAS"},
  {j:"Science Translational Medicine", o:"Science · AAAS"},
  {j:"Science Robotics", o:"Science · AAAS"},
  {j:"eLife", o:"eLife"},
  {j:"PNAS", o:"PNAS"},
  {j:"PNAS Nexus", o:"PNAS"},
  {j:"Proceedings of the National Academy of Sciences", o:"PNAS"},
  {j:"The EMBO Journal", o:"EMBO Press"},
  {j:"EMBO Reports", o:"EMBO Press"},
  {j:"Molecular Systems Biology", o:"EMBO Press"},
  {j:"EMBO Molecular Medicine", o:"EMBO Press"},
  {j:"Journal of Cell Biology", o:"Rockefeller University Press"},
  {j:"Journal of Experimental Medicine", o:"Rockefeller University Press"},
  {j:"Journal of General Physiology", o:"Rockefeller University Press"},
  {j:"mBio", o:"ASM Journals"},
  {j:"mSystems", o:"ASM Journals"},
  {j:"mSphere", o:"ASM Journals"},
  {j:"Microbiology Spectrum", o:"ASM Journals"},
  {j:"Journal of Bacteriology", o:"ASM Journals"},
  {j:"Journal of Virology", o:"ASM Journals"},
  {j:"Applied and Environmental Microbiology", o:"ASM Journals"},
  {j:"Antimicrobial Agents and Chemotherapy", o:"ASM Journals"},
  {j:"Infection and Immunity", o:"ASM Journals"},
  {j:"Journal of Clinical Microbiology", o:"ASM Journals"},
  {j:"PLOS Biology", o:"PLOS"},
  {j:"PLOS ONE", o:"PLOS"},
  {j:"PLOS Genetics", o:"PLOS"},
  {j:"PLOS Computational Biology", o:"PLOS"},
  {j:"PLOS Pathogens", o:"PLOS"},
  {j:"PLOS Medicine", o:"PLOS"},
  {j:"The FEBS Journal", o:"FEBS Press"},
  {j:"FEBS Letters", o:"FEBS Press"},
  {j:"FEBS Open Bio", o:"FEBS Press"},
  {j:"Molecular Oncology", o:"FEBS Press"},
  {j:"Development", o:"The Company of Biologists"},
  {j:"Journal of Cell Science", o:"The Company of Biologists"},
  {j:"Journal of Experimental Biology", o:"The Company of Biologists"},
  {j:"Disease Models &amp; Mechanisms", o:"The Company of Biologists"},
  {j:"Biology Open", o:"The Company of Biologists"},
  {j:"JAMA", o:"JAMA Network"},
  {j:"JAMA Neurology", o:"JAMA Network"},
  {j:"JAMA Psychiatry", o:"JAMA Network"},
  {j:"BMJ", o:"BMJ"},
  {j:"BMJ Open", o:"BMJ"},
  {j:"BMJ Global Health", o:"BMJ"},
  {j:"Journal of the American Chemical Society", o:"ACS Publications"},
  {j:"ACS Chemical Biology", o:"ACS Publications"},
  {j:"ACS Nano", o:"ACS Publications"},
  {j:"Biochemistry", o:"ACS Publications"},
  {j:"Journal of Medicinal Chemistry", o:"ACS Publications"},
  {j:"ACS Chemical Neuroscience", o:"ACS Publications"},
  {j:"Analytical Chemistry", o:"ACS Publications"},
  {j:"Journal of Proteome Research", o:"ACS Publications"},
  {j:"IEEE Transactions (all titles)", o:"IEEE"},
  {j:"IEEE Access", o:"IEEE"},
  {j:"ACM journals and conferences", o:"ACM"},
  {j:"Journal of Experimental Psychology", o:"APA Publishing"},
  {j:"Psychological Review", o:"APA Publishing"},
  {j:"Behavioral Neuroscience", o:"APA Publishing"},
   {j:"Advanced Materials", o:"Wiley"},
  {j:"Advanced Functional Materials", o:"Wiley"},
  {j:"Advanced Energy Materials", o:"Wiley"},
  {j:"Advanced Science", o:"Wiley"},
  {j:"Small", o:"Wiley"},
  {j:"Angewandte Chemie", o:"Wiley"},
  {j:"Angewandte Chemie International Edition", o:"Wiley"},
  {j:"Chemistry &ndash; A European Journal", o:"Wiley"},
  {j:"ChemBioChem", o:"Wiley"},
  {j:"ChemPhysChem", o:"Wiley"},
  {j:"Macromolecular Rapid Communications", o:"Wiley"},
  {j:"Langmuir", o:"ACS Publications"},
  {j:"Nano Letters", o:"ACS Publications"},
  {j:"ACS Catalysis", o:"ACS Publications"},
  {j:"Chemical Reviews", o:"ACS Publications"},
  {j:"Chemistry of Materials", o:"ACS Publications"},
  {j:"ACS Applied Materials &amp; Interfaces", o:"ACS Publications"},
  {j:"Macromolecules", o:"ACS Publications"},
  {j:"Organic Letters", o:"ACS Publications"},
  {j:"The Journal of Organic Chemistry", o:"ACS Publications"},
  {j:"Inorganic Chemistry", o:"ACS Publications"},
  {j:"JACS Au", o:"ACS Publications"},
  {j:"ACS Omega", o:"ACS Publications"},
  {j:"ACS Sensors", o:"ACS Publications"},
  {j:"Bioconjugate Chemistry", o:"ACS Publications"},
  {j:"ACS Synthetic Biology", o:"ACS Publications"},
  {j:"The Journal of Physical Chemistry A", o:"ACS Publications"},
  {j:"The Journal of Physical Chemistry B", o:"ACS Publications"},
  {j:"The Journal of Physical Chemistry C", o:"ACS Publications"},
  {j:"The Journal of Physical Chemistry Letters", o:"ACS Publications"},
  {j:"Tetrahedron", o:"Elsevier"},
  {j:"Tetrahedron Letters", o:"Elsevier"},
  {j:"Polymer", o:"Elsevier"},
  {j:"Carbon", o:"Elsevier"},
  {j:"Journal of Catalysis", o:"Elsevier"},
  {j:"Electrochimica Acta", o:"Elsevier"},
  {j:"Journal of Colloid and Interface Science", o:"Elsevier"},
  {j:"Materials Today", o:"Elsevier"},
  {j:"Acta Materialia", o:"Elsevier"},
  {j:"Chemical Engineering Journal", o:"Elsevier"},
  {j:"Journal of Chromatography A", o:"Elsevier"},
  {j:"Analytica Chimica Acta", o:"Elsevier"},
  {j:"Nature Materials", o:"Springer Nature"},
  {j:"Nature Nanotechnology", o:"Springer Nature"},
  {j:"Nature Catalysis", o:"Springer Nature"},
  {j:"Nature Energy", o:"Springer Nature"},
  {j:"Communications Chemistry", o:"Springer Nature"},
  {j:"Communications Materials", o:"Springer Nature"},
  {j:"Scientific Data", o:"Springer Nature"},
  {j:"Journal of Materials Science", o:"Springer Nature"},
  {j:"Chem", o:"Cell Press"},
  {j:"Joule", o:"Cell Press"},
  {j:"Matter", o:"Cell Press"},
  {j:"Cell Reports Physical Science", o:"Cell Press"},
   {j:"Chemical Science", o:"Royal Society of Chemistry"},
  {j:"Soft Matter", o:"Royal Society of Chemistry"},
  {j:"Nanoscale", o:"Royal Society of Chemistry"},
  {j:"Chemical Communications", o:"Royal Society of Chemistry"},
  {j:"Chemical Society Reviews", o:"Royal Society of Chemistry"},
  {j:"Physical Chemistry Chemical Physics", o:"Royal Society of Chemistry"},
  {j:"Journal of Materials Chemistry A", o:"Royal Society of Chemistry"},
  {j:"Journal of Materials Chemistry B", o:"Royal Society of Chemistry"},
  {j:"Journal of Materials Chemistry C", o:"Royal Society of Chemistry"},
  {j:"Green Chemistry", o:"Royal Society of Chemistry"},
  {j:"Analyst", o:"Royal Society of Chemistry"},
  {j:"Lab on a Chip", o:"Royal Society of Chemistry"},
  {j:"RSC Advances", o:"Royal Society of Chemistry"},
  {j:"Digital Discovery", o:"Royal Society of Chemistry"},
  {j:"bioRxiv", o:"bioRxiv"},
  {j:"medRxiv", o:"bioRxiv"}
];

const POLICY_REGISTER = [

/* ================= STANDARDS BODIES ================= */
{
  org: "ICMJE",
  full: "International Committee of Medical Journal Editors",
  cat: "standards",
  verdict: "Disclose AI assistance in both the cover letter and the manuscript · AI cannot be an author · reviewers must protect confidentiality.",
  chips: [{t:"Writing: disclose",s:"ok"},{t:"Authorship: prohibited",s:"stop"},{t:"Peer review: confidentiality",s:"warn"}],
  writing: "Authors must disclose whether they used AI-assisted technologies, large language models, chatbots, image creators, in producing submitted work, describing the use in both the cover letter and the manuscript itself. The 2026 revision introduces a dedicated section covering AI across the full publishing workflow: manuscript preparation, peer review and editorial decision-making.",
  images: "AI-generated images fall within the disclosure requirement, and authors must ensure the absence of plagiarism in AI-produced text <em>and</em> images.",
  review: "Reviewers must not upload manuscripts to platforms that cannot guarantee confidentiality, and must disclose to the journal whether and how AI was used in evaluating a manuscript or drafting review comments.",
  screening: "ICMJE sets norms rather than running tools, but because most medical and life-science journals adopt its recommendations, its rules propagate into hundreds of journals' own policies.",
  forYou: "If your target journal is in medicine or the life sciences and its own policy is vague, assume ICMJE applies.",
  covers: "Underpins most medical and life-science journal policies worldwide",
  url: "https://www.icmje.org/recommendations/",
  verified: "July 2026"
},
{
  org: "COPE",
  full: "Committee on Publication Ethics",
  cat: "standards",
  verdict: "AI cannot be an author · authors carry full responsibility · editors should not reject on suspicion of AI use alone.",
  chips: [{t:"Writing: disclose",s:"ok"},{t:"Authorship: prohibited",s:"stop"},{t:"Suspicion is not grounds",s:"ok"}],
  writing: "COPE's position, joined by WAME and the JAMA Network, is that AI tools cannot meet authorship criteria because they cannot take responsibility for the work. Authors are responsible for the accuracy and quality of all content in a submission, however it was produced.",
  images: "Covered by the same accountability principle: the author answers for every figure, regardless of the tool used to make it.",
  review: "COPE guidance asks reviewers to disclose AI use and preserve confidentiality.",
  screening: "COPE co-founded United2Act with STM to tackle paper mills collectively, and its guidance shapes how publishers handle large-scale integrity cases. Notably, COPE advises editors <em>not</em> to reject manuscripts on suspicion of AI use alone, the focus should be actual policy violations or integrity problems, not detector scores.",
  forYou: "This line protects you too: an AI-detector flag is not, on its own, evidence of anything.",
  covers: "Members include nearly every major publisher and thousands of journals",
  url: "https://publicationethics.org/guidance/cope-position/authorship-and-ai-tools",
  verified: "July 2026"
},
{
  org: "WAME · CSE",
  full: "World Association of Medical Editors · Council of Science Editors",
  cat: "standards",
  verdict: "Chatbots cannot be authors · state transparently how AI was used · the author answers for its output.",
  chips: [{t:"Writing: disclose",s:"ok"},{t:"Authorship: prohibited",s:"stop"}],
  writing: "WAME asks authors to be transparent about how chatbots were used and to acknowledge all sources including AI-generated material. CSE guidance similarly asks for disclosure of ChatGPT, chatbot and LLM use, and confirms such tools do not qualify for authorship.",
  images: "Both bodies treat AI-generated images as requiring the same disclosure and the same human accountability as text.",
  review: "Editors are advised to have appropriate tools to help detect AI-generated or AI-modified content.",
  screening: "Norm-setting rather than tool-running; both feed into journal-level policy across medicine and the sciences.",
  forYou: "Useful when a small or society journal has no policy of its own, these are the defaults it will fall back on.",
  covers: "Medical and science editor communities worldwide",
  url: "https://wame.org/page3.php?id=106",
  verified: "July 2026"
},

{
  org: "UGC · theses",
  full: "University Grants Commission, thesis and dissertation context",
  cat: "standards",
  verdict: "No AI-specific regulation yet · the 2018 plagiarism framework governs theses, and undisclosed AI text is being treated as plagiarism under it.",
  chips: [{t:"Writing: 2018 rules govern",s:"warn"},{t:"Undisclosed AI: plagiarism",s:"stop"}],
  writing: "The UGC (Promotion of Academic Integrity and Prevention of Plagiarism) Regulations, 2018 remain the governing framework for Indian theses: graded similarity levels with escalating penalties, mandatory screening, and Academic Misconduct Panels. The UGC has issued no formal AI amendment, but universities have begun applying the existing framework to AI-generated text, including rejecting theses where undisclosed AI-derived content pushed similarity beyond permitted levels. In the absence of a dedicated rule, undisclosed AI writing in a thesis sits in the worst of both worlds: permitted by no policy, and indefensible under the plagiarism framework.",
  images: "Not addressed by the 2018 regulations.",
  review: "Thesis evaluation practice varies by university; there is no national rule on examiner use of AI.",
  screening: "Similarity screening of theses is mandatory nationally; at NCBS this is the iThenticate check recorded on the pre-submission checklist.",
  forYou: "Your thesis is the one document no journal policy covers. The safe habit is the discipline the strict journals teach: polishing your own text is one thing, letting a model draft is another, and either way keep a record of what you used, because the framework that will judge the thesis was written before AI existed.",
  covers: "PhD and MSc theses at Indian higher educational institutions, including the TIFR deemed university",
  url: "https://www.ugc.gov.in/pdfnews/7771545_academic-integrity-Regulation2018.pdf",
  verified: "August 2026"
},

/* ================= PUBLISHERS ================= */
{
  org: "Springer Nature",
  full: "Nature Portfolio · BMC · Springer · npj · Communications journals",
  cat: "publisher",
  verdict: "Document LLM use in Methods, copy editing exempt · AI-generated images not permitted at all · reviewers may not upload your manuscript to any AI tool.",
  chips: [{t:"Writing: Methods",s:"ok"},{t:"Copy editing: exempt",s:"ok"},{t:"Authorship: prohibited",s:"stop"},{t:"Images: prohibited",s:"stop"},{t:"Peer review: prohibited",s:"stop"}],
  writing: "LLMs do not satisfy Springer Nature's authorship criteria, because authorship carries accountability that cannot be applied to a model. Use of an LLM must be documented in the Methods section, or a suitable alternative section where no Methods exists. Uniquely among the majors, Springer Nature carves out an explicit exemption: <strong>AI-assisted copy editing does not need to be declared</strong>, defined as AI-assisted improvement of human-written text for readability, style, grammar, spelling, punctuation and tone. That exemption stops where generative editorial work or autonomous content creation begins, and human accountability for the final text is required either way.",
  images: "One of the strictest positions in publishing. Citing unresolved copyright law alongside integrity concerns, Springer Nature journals cannot permit generative AI images or video for publication at all. Three exceptions: art from agencies with contractual relationships that created it lawfully; images directly referenced in a piece specifically <em>about</em> AI, reviewed case by case; and generative tools built on attributable, checkable scientific data. Every exception must be labelled as AI-generated in the image field. Separately, and easy to miss, <strong>non-generative</strong> machine-learning tools used to manipulate, combine or enhance existing images must be disclosed in the relevant caption at submission for case-by-case review.",
  review: "Peer reviewers are asked not to upload manuscripts into generative AI tools at all, on confidentiality and reliability grounds; if any part of their evaluation was AI-supported, they must declare it transparently in the report.",
  screening: "The most extensive in-house toolset in the industry. A nonsense-text detector (internally 'Geppetto') scores manuscript sections for AI-generated text and triggers human checks, deployed since November 2023 across most journal and book submissions, and since donated to the STM Integrity Hub. SnappShot analyses gel and blot images for duplication. A non-standard-phrase detector draws on the public 'tortured phrases' catalogue from the Problematic Paper Screener, and an irrelevant-reference checker flags citations unrelated to the manuscript.",
  forYou: "The copy-editing exemption is real but narrow, polishing your own sentences is fine and needs no declaration; having the model draft the paragraph does not qualify. And do not put an AI-made schematic in a Nature-family paper.",
  covers: "Nature, Nature Methods, Nature Communications, npj series, BMC series, Scientific Reports, Communications Biology and the wider Springer portfolio",
  url: "https://www.nature.com/nature-portfolio/editorial-policies/ai",
  verified: "July 2026"
},
{
  org: "Elsevier",
  full: "Elsevier journals · The Lancet family · Cell Press (separate entry)",
  cat: "publisher",
  verdict: "Writing assistance permitted only to improve language and readability, declared in a dedicated statement before the references · AI-generated images prohibited · reviewers prohibited.",
  chips: [{t:"Writing: language only",s:"warn"},{t:"Disclosure: dedicated statement",s:"warn"},{t:"Authorship: prohibited",s:"stop"},{t:"Images: prohibited",s:"stop"},{t:"Peer review: prohibited",s:"stop"}],
  writing: "Narrower than most. Generative AI may be used in the writing process <strong>only to improve language and readability</strong>, not to generate content, argument or interpretation. Disclosure goes in a dedicated AI statement placed before the references (policy updated September 2025), not buried in the Acknowledgements. Spelling and grammar checkers integrated into word processors are exempt. Reference managers used without a generative option need no declaration, but if any AI tool selects, collates, generates or edits references that must be declared, and Elsevier warns explicitly that fabricated or hallucinated references may lead to rejection. Permitted supportive uses include summarising literature in preparation for writing, helping structure content, improving clarity, and checking a manuscript against guidelines.",
  images: "Generative AI may not be used to create or alter images in a submitted manuscript. AI used within formal research design or methods is a separate matter and belongs in the Methods section, study design, code development or data analysis are explicitly not restricted by this policy.",
  review: "Editors and reviewers must not upload manuscripts, or any part of them, into generative AI tools, on confidentiality grounds. The Lancet family maintains the same prohibition.",
  screening: "Check Integrity, expanded in March 2026 across nearly 2,000 Elsevier journals, screens submissions automatically for publishing-ethics breaches, unauthorised authorship changes, editorial conflicts of interest, routing flags to specialist integrity analysts rather than editors.",
  forYou: "The 'language and readability only' line is the tightest of the majors, and the dedicated pre-references statement is a formatting requirement people routinely miss. Check every reference against the original source before submitting.",
  covers: "Around 2,000 Elsevier journals including The Lancet family; Cell Press adds further restrictions",
  url: "https://www.elsevier.com/about/policies-and-standards/generative-ai-policies-for-journals",
  verified: "July 2026"
},
{
  org: "Cell Press",
  full: "Cell · Molecular Cell · Neuron · Immunity · Current Biology · Cell Reports · iScience · Heliyon",
  cat: "publisher",
  verdict: "The strictest image rule in biology, no AI adjustment of brightness, contrast or colour balance in any data image · disclose writing use in STAR Methods · no AI graphical abstracts.",
  chips: [{t:"Writing: STAR Methods",s:"ok"},{t:"Authorship: prohibited",s:"stop"},{t:"Data images: prohibited",s:"stop"},{t:"Graphical abstracts: prohibited",s:"stop"},{t:"Cover art: by permission",s:"warn"}],
  writing: "Authors must declare generative AI use in scientific writing at submission; the guidance covers the writing process, not the use of AI to analyse data as part of the research itself. Cell Press journals require the declaration under <strong>STAR Methods (Method Details)</strong>, a structural requirement beyond what general Elsevier journals ask for, and Elsevier's broader policy applies on top.",
  images: "Read this carefully, because it goes further than any other major publisher. Cell Press does not permit generative AI or AI-assisted tools to create <em>or alter</em> research or data images, explicitly including adjustments of brightness, contrast or colour balance in any image presenting experimental or observational data. General-purpose generative AI image tools may not be used to create graphical abstracts. Cover art produced with generative AI is not permitted at Cell, and elsewhere may be allowed only with prior editorial permission, cleared rights and correct attribution. An editorial exception exists only where AI is integral to the research being described. Structural renderings from PyMOL or ChimeraX are not 'AI-generated images'. Authors are asked to verify before submission that every figure can be matched back to the original unprocessed data.",
  review: "Reviewers are prohibited from using AI on manuscripts, in line with Elsevier policy, confidentiality plus the irreplaceability of human expertise.",
  screening: "All accepted manuscripts are screened for image irregularities. Concerns are assessed by journal editors with the research integrity team following COPE guidance, and may trigger requests for the original unprocessed data and an account of how the figures were prepared.",
  forYou: "If you work with blots or microscopy and publish in Cell Press titles, the safest habit is simple: never let any AI-enabled 'enhance' feature touch a data image, and keep the unprocessed originals findable, which is exactly what the RIO deposition process is for.",
  covers: "Cell, Molecular Cell, Cancer Cell, Immunity, Neuron, Cell Metabolism, Cell Reports and family, Current Biology, iScience, Heliyon, Joule, Matter, Chem, Med, Patterns, One Earth, Structure, Molecular Plant",
  url: "https://www.cell.com/cell/information-for-authors/journal-policies",
  verified: "July 2026"
},
{
  org: "Wiley",
  full: "Wiley journals and society titles · Advanced series · Hindawi",
  cat: "publisher",
  verdict: "Disclosure with human accountability · AI cannot be an author · one of the largest automated screening stacks in publishing, running before peer review.",
  chips: [{t:"Writing: disclose",s:"ok"},{t:"Authorship: prohibited",s:"stop"},{t:"Screening: ~30 checks",s:"warn"}],
  writing: "Wiley's best-practice guidelines on research integrity and publishing ethics require transparent disclosure of AI assistance and place accountability with the human authors. The framework applies across Wiley journals including the many society-owned titles published on the Wiley platform, but individual society journals may add their own requirements, so check the specific title.",
  images: "AI-generated or AI-altered images are treated as an integrity risk and must be disclosed; data images are expected to represent what was observed.",
  review: "Reviewers are expected to preserve confidentiality and not upload manuscripts to external AI tools.",
  screening: "Research Exchange Screening consolidates around 30 automated integrity checks into the submission workflow, Wiley's proprietary Papermill Detection tool plus third-party tools, running <em>before</em> peer review begins. The papermill service covers six areas: similarity to known paper-mill papers, problematic or 'tortured' phrase recognition, irregular author publishing patterns, researcher identity verification, generative-AI content detection, and journal-scope relevance. Wiley states flags go to an editor for closer consideration rather than triggering automatic rejection.",
  forYou: "Because Wiley publishes for hundreds of societies, the platform policy is the floor and the society journal's own guidelines may sit above it. Read the specific journal page, not just the Wiley hub.",
  covers: "Advanced Science, Small, Aggregate, InfoMat, Human Brain Mapping, Journal of Extracellular Vesicles, FEBS Press titles, Cochrane Library and many society journals",
  url: "https://authorservices.wiley.com/ethics-guidelines/index.html",
  verified: "July 2026"
},
{
  org: "Taylor &amp; Francis",
  full: "Taylor &amp; Francis · Routledge · Dove Medical Press",
  cat: "publisher",
  verdict: "Responsible use permitted, declare tool name, version number, how and why it was used · creating or altering images with AI is forbidden.",
  chips: [{t:"Writing: disclose in detail",s:"ok"},{t:"Authorship: prohibited",s:"stop"},{t:"Images: prohibited",s:"stop"}],
  writing: "Generative AI tools cannot be listed as authors because they cannot assume responsibility for content or manage copyright and licensing, responsibilities described as uniquely human. Authors must acknowledge any use within the article or book with a statement giving <strong>the full name of the tool including version number</strong>, how it was used, and the reason for use; article submissions carry a specific AI-usage disclosure statement. Authors remain accountable for the originality, validity and integrity of the submission, references included. Book authors and editors must disclose intent to use generative AI at the earliest stage.",
  images: "Taylor &amp; Francis forbids using generative AI to create or alter images. Permitted uses are framed around tools that respect data security, confidentiality and copyright.",
  review: "Reviewers are expected to maintain confidentiality; uploading manuscripts to external tools conflicts with that expectation.",
  screening: "An early adopter of the STM papermill detection tooling, alongside participation in shared industry screening infrastructure.",
  forYou: "The version-number requirement is unusual and enforceable, record which model and version you used while you are using it, not months later at submission.",
  covers: "Taylor &amp; Francis and Routledge journals, Dove Medical Press",
  url: "https://taylorandfrancis.com/our-policies/ai-policy/",
  verified: "July 2026"
},
{
  org: "SAGE",
  full: "SAGE Publishing",
  cat: "publisher",
  verdict: "Among the more permissive, idea generation and gap-finding allowed, provided you declare it and verify every output.",
  chips: [{t:"Writing: disclose",s:"ok"},{t:"Ideation: permitted",s:"ok"},{t:"Authorship: prohibited",s:"stop"}],
  writing: "SAGE explicitly permits uses that stricter publishers do not, identifying research gaps, generating ideas, refining language, on three conditions: the use is declared, the outputs are verified by the author, and the tool's limitations are respected. AI cannot be credited as an author.",
  images: "Assistive and generative AI affecting figures must be declared; data integrity expectations are unchanged.",
  review: "Confidentiality obligations apply to reviewers using any external tool.",
  screening: "A partner in Wiley's Papermill Detection testing alongside IEEE, and a participant in shared industry integrity infrastructure.",
  forYou: "Permissive is not the same as silent, 'you may brainstorm with it' still comes with 'and you must say so'.",
  covers: "SAGE journals across the social sciences, medicine and STEM",
  url: "https://us.sagepub.com/en-us/nam/artificial-intelligence-policy",
  verified: "July 2026"
},
{
  org: "Oxford University Press",
  full: "Oxford Academic journals",
  cat: "publisher",
  verdict: "AI does not qualify for authorship and journals actively screen author lists · disclose in the cover letter <em>and</em> the Methods or Acknowledgements.",
  chips: [{t:"Writing: disclose twice",s:"warn"},{t:"Authorship: screened",s:"stop"}],
  writing: "Oxford Academic states that natural-language tools driven by AI do not qualify as authors, and that journals will screen author lists for them. Use of AI to help generate content, write code or process data should be disclosed both in the cover letter to editors and in the Methods or Acknowledgements section.",
  images: "AI-generated images fall under the same disclosure requirement, with data-integrity expectations governed by each journal's figure guidelines.",
  review: "Standard confidentiality expectations apply to reviewers.",
  screening: "Text-similarity screening is routine; author-list screening for AI entries is explicitly stated.",
  forYou: "Two places, not one, the cover letter disclosure is the step most often forgotten at OUP titles.",
  covers: "Nucleic Acids Research, Bioinformatics, Briefings in Bioinformatics, Molecular Biology and Evolution, GigaScience, Brain Communications and the wider Oxford Academic list",
  url: "https://academic.oup.com/pages/authoring/journals/preparing_your_manuscript/ethics",
  verified: "July 2026"
},
{
  org: "Cambridge University Press",
  full: "Cambridge University Press journals and books",
  cat: "publisher",
  verdict: "AI may not be listed as an author on any Cambridge work · use must be declared, accountability stays human.",
  chips: [{t:"Writing: disclose",s:"ok"},{t:"Authorship: prohibited",s:"stop"}],
  writing: "Cambridge's AI ethics policy holds that AI does not meet its authorship requirements, given the need for accountability. AI and LLM tools may not be listed as authors on any scholarly work published by Cambridge; use must be declared and human authors remain responsible.",
  images: "Declared under the same policy; figure integrity governed by journal-level guidelines.",
  review: "Confidentiality expectations apply.",
  screening: "Participates in industry-standard similarity and integrity screening.",
  forYou: "Straightforward policy, the declaration is the whole obligation, so make it explicit rather than implied.",
  covers: "Cambridge journals including Acta Numerica, Language Teaching, ReCALL, Natural Language Processing",
  url: "https://www.cambridge.org/core/services/authors/publishing-ethics",
  verified: "July 2026"
},
{
  org: "MDPI",
  full: "MDPI journals",
  cat: "publisher",
  verdict: "Disclose generative AI in manuscript preparation · AI cannot be an author · portfolio-wide image screening via Proofig.",
  chips: [{t:"Writing: disclose",s:"ok"},{t:"Authorship: prohibited",s:"stop"},{t:"Images: screened",s:"warn"}],
  writing: "MDPI follows COPE-aligned guidance: generative AI used in preparing a manuscript must be acknowledged, authors are fully responsible for content, and AI tools do not qualify for authorship.",
  images: "MDPI has signed a multi-year agreement to integrate Proofig across its portfolio, making automated image-integrity screening a standing part of the workflow.",
  review: "Reviewer confidentiality obligations apply.",
  screening: "Proofig portfolio-wide, plus participation in the STM Integrity Hub. MDPI's own analysis puts image and data manipulation at roughly 15% of 2025 retractions across publishing, with numbers easing as detection tooling spreads.",
  forYou: "High-volume publishers screen hardest. Expect figures to be checked automatically.",
  covers: "The MDPI journal portfolio",
  url: "https://www.mdpi.com/ethics",
  verified: "July 2026"
},
{
  org: "Frontiers",
  full: "Frontiers Media",
  cat: "publisher",
  verdict: "No AI co-authors · acknowledge AI-produced <em>or AI-edited</em> content, and describe it in Methods where applicable.",
  chips: [{t:"Writing: disclose",s:"ok"},{t:"Authorship: prohibited",s:"stop"}],
  writing: "Generative AI may not be listed as an author or co-author. Written or visual content produced by, or edited using, generative AI must be acknowledged in the Acknowledgements section, and in the Methods where applicable.",
  images: "Visual content produced <em>or edited</em> with generative AI falls explicitly within the acknowledgement requirement, a broader phrasing than text-only policies.",
  review: "Standard confidentiality expectations.",
  screening: "Frontiers operates its own AI-assisted integrity screening across submissions.",
  forYou: "Note the phrase 'or edited using', editing an existing figure with an AI tool triggers disclosure here.",
  covers: "The Frontiers in… journal series",
  url: "https://www.frontiersin.org/guidelines/policies-and-publication-ethics",
  verified: "July 2026"
},

{
  org: "Royal Society of Chemistry",
  full: "RSC journals · Chemical Science, Soft Matter, Nanoscale, ChemComm, PCCP, Journal of Materials Chemistry, RSC Advances and the wider portfolio",
  cat: "publisher",
  verdict: "Declare generative AI use twice, in the cover letter at submission and in the Acknowledgements with tool, version and how it was used · AI must not alter images.",
  chips: [{t:"Writing: cover letter + Acknowledgements",s:"warn"},{t:"Authorship: prohibited",s:"stop"},{t:"Images: no AI alteration",s:"stop"}],
  writing: "AI tools such as ChatGPT or other large language models cannot be listed as an author on a submitted work. If generative AI tools have been used in generating any part of the manuscript, this must be declared at submission within the cover letter, with the details given in the Acknowledgements: the name of the tool, its version, and how it was used. Authors are fully responsible and accountable for the content of their article, including any parts produced by an AI tool.",
  images: "Generative or AI-assisted tools must not be used to alter images in submitted manuscripts, including adding, removing, moving or obscuring features. AI-created graphics used purely for illustration need a brief description in the figure caption and the tool details in the Acknowledgements.",
  review: "The author-facing policy does not set out reviewer rules; RSC&rsquo;s reviewer-responsibility pages govern there, with the usual confidentiality expectations.",
  screening: "Standard similarity screening across the portfolio.",
  forYou: "The cover-letter declaration is the step people miss, and it is checked at submission. Record the tool and version while you work, not afterwards.",
  covers: "Chemical Science, Soft Matter, Nanoscale, Chemical Communications, Chem Soc Rev, PCCP, Journal of Materials Chemistry A/B/C, Green Chemistry, Analyst, Lab on a Chip, RSC Advances, Digital Discovery",
  url: "https://www.rsc.org/journals-books-databases/author-and-reviewer-hub/authors-information/responsibilities/",
  verified: "August 2026"
},

/* ================= JOURNALS & SOCIETIES ================= */
{
  org: "Science · AAAS",
  full: "Science, Science Advances, Science Immunology, Science Robotics, Science Signaling, Science Translational Medicine",
  cat: "journal",
  verdict: "Permitted, but with the most detailed disclosure in publishing, tool, version and <em>the full prompt</em> in Methods · every image screened by Proofig before peer review.",
  chips: [{t:"Writing: full prompt required",s:"warn"},{t:"Authorship: prohibited",s:"stop"},{t:"Images: Proofig screened",s:"warn"},{t:"Peer review: prohibited",s:"stop"}],
  writing: "Science's November 2023 revision relaxed an earlier near-prohibition. AI-assisted technologies may now be used as components of a study or as aids in writing or presentation, noted in the cover letter and the Acknowledgements, with detailed information in the Methods, including <strong>the full prompt used in producing the work</strong>, plus the AI tool and its version. That prompt-level requirement is the strictest disclosure standard among major venues. Sources cited may not be authored or co-authored by AI. Authors are accountable for accuracy, for the absence of plagiarism, and for guarding against bias introduced by AI.",
  images: "From 2024 all six Science family journals screen images with Proofig, an AI image-analysis tool that Science's Editor-in-Chief described as the image equivalent of iThenticate. It had been running quietly for about six months before the announcement. Reports are reviewed before external peer review. Serious errors leading to non-publication run at under 1% of papers, but the screen catches both honest mistakes and deliberate manipulation.",
  review: "Reviewers may not use generative AI on manuscripts.",
  screening: "Proofig across all six journals for images; iThenticate for text, in use for over seven years.",
  forYou: "Keep your prompts. At Science you may be asked to publish them, and reconstructing a prompt from memory months later is not a defensible record.",
  covers: "All six Science family journals",
  url: "https://www.science.org/content/page/science-journals-editorial-policies",
  verified: "July 2026"
},
{
  org: "eLife",
  full: "eLife",
  cat: "journal",
  verdict: "Disclose in Methods with enough detail to assess scope · AI figures prohibited · and the peer reviews are public, so gaps in disclosure are visible to everyone.",
  chips: [{t:"Writing: Methods",s:"ok"},{t:"Authorship: prohibited",s:"stop"},{t:"Images: prohibited",s:"stop"},{t:"Reviews: public",s:"warn"}],
  writing: "eLife follows ICMJE- and COPE-aligned principles. AI use in manuscript preparation is described in the Methods with enough detail for readers to assess its scope, a qualitative standard rather than a box to tick.",
  images: "AI-created figures, illustrations and visualisations are not permitted in the manuscript.",
  review: "Under eLife's publish-then-review model, reviewer comments are published alongside every paper and the eLife assessment is part of the record. A reviewer's observation that a section reads as AI-generated with no disclosure becomes permanently public, inadequate disclosure is more exposed here than almost anywhere else.",
  screening: "Standard similarity and integrity checks, with the added transparency of public review.",
  forYou: "Disclose generously at eLife. The cost of over-disclosing is nil; the cost of under-disclosing is a permanent public comment attached to your paper.",
  covers: "eLife",
  url: "https://elifesciences.org/inside-elife",
  verified: "July 2026"
},
{
  org: "PNAS",
  full: "Proceedings of the National Academy of Sciences · PNAS Nexus",
  cat: "journal",
  verdict: "Dual disclosure, Methods <em>and</em> the Author Contributions statement · no AI authorship · AI images prohibited.",
  chips: [{t:"Writing: disclose twice",s:"warn"},{t:"Authorship: prohibited",s:"stop"},{t:"Images: prohibited",s:"stop"}],
  writing: "PNAS and PNAS Nexus require that AI used to help generate any part of the work be clearly acknowledged in the Materials and Methods, or the Acknowledgements where no Methods section exists, and additionally flagged in the <strong>Author Contributions</strong> statement. This dual requirement is unusual: the Methods entry gives the detail, the Author Contributions entry surfaces it to anyone scanning the paper.",
  images: "AI-created figures, illustrations and visualisations are not permitted.",
  review: "Confidentiality expectations apply to reviewers.",
  screening: "Standard similarity and image screening under NAS editorial authority.",
  forYou: "The Author Contributions line is the one people miss, a Methods-only disclosure is incomplete at PNAS.",
  covers: "PNAS, PNAS Nexus",
  url: "https://www.pnas.org/author-center/editorial-and-journal-policies",
  verified: "July 2026"
},
{
  org: "EMBO Press",
  full: "The EMBO Journal · EMBO Reports · Molecular Systems Biology · EMBO Molecular Medicine",
  cat: "journal",
  verdict: "AI restricted to improving style and quality of human-generated text and images · every image-based figure analysed before acceptance, with source data on request.",
  chips: [{t:"Writing: style only",s:"warn"},{t:"Authorship: prohibited",s:"stop"},{t:"Images: 100% screened",s:"warn"},{t:"Source data: on request",s:"ok"}],
  writing: "EMBO's position is that AI use should be primarily restricted to improving the style, accessibility or quality of human-generated text and images, including schemata and data figures, with any AI-assembled part of an article declared. Accountability stays with the authors.",
  images: "This is where EMBO stands apart. Journal staff analyse <strong>all</strong> image-based data in every manuscript before acceptance, offered as a free service to authors and the community; a dedicated data integrity analyst screens figures and source data. Editors may request source data for any figure as a condition of publication, and the SourceData initiative captures machine-readable metadata from figures. EMBO publishes a three-tier classification of image and data aberrations, and states plainly that screening cannot catch everything and that not every anomaly implies intent to deceive. Where evidence points to serious manipulation, the author's institution is alerted.",
  review: "Standard confidentiality expectations; CrossCheck screens submitted content for plagiarism including self-plagiarism.",
  screening: "Systematic pre-publication image screening across all EMBO Press journals, with post-publication follow-up where conclusions are affected. CrossCheck for text.",
  forYou: "EMBO will likely ask for your source data, organise the deposit so any figure's underlying data can be produced on a day's notice. This is the single clearest case for the RIO deposition workflow.",
  covers: "The four EMBO Press journals",
  url: "https://www.embopress.org/image-integrity",
  verified: "July 2026"
},
{
  org: "Rockefeller University Press",
  full: "Journal of Cell Biology · Journal of Experimental Medicine · Journal of General Physiology",
  cat: "journal",
  verdict: "The original image-screening programme, every image in every figure of every accepted paper is inspected, and acceptance can be revoked.",
  chips: [{t:"Images: 100% inspected",s:"stop"},{t:"Originals: on demand",s:"warn"},{t:"Authorship: prohibited",s:"stop"}],
  writing: "Standard community norms apply: AI cannot be an author and use must be disclosed. But RUP's distinguishing policy is about images, not text.",
  images: "JCB pioneered systematic image screening and still screens every image in every figure of every accepted manuscript against its digital-image standards, the guidelines many other journals adopted into their author instructions without adopting the enforcement. Adjusting the contrast of an entire figure is acceptable; adjusting one part of an image is not, because that changes the meaning of the data. If figure resolution is insufficient for proper screening, the original data is requested, and failure to locate originals delays the manuscript. Historically, acceptance has been revoked for around 1% of papers that had already passed peer review, either because manipulation affected interpretation, or because authors could not produce the original images.",
  review: "Standard confidentiality expectations.",
  screening: "Human expert inspection of every accepted paper, historically using controlled adjustments in Photoshop rather than relying solely on automated tools, RUP has publicly argued that weak automated screening creates a false sense of security. The JCB DataViewer additionally lets readers inspect the original image data underlying figures.",
  forYou: "If you publish at JCB or JEM, assume every panel will be examined and that you may be asked for raw files. Losing the originals is itself a publication risk.",
  covers: "JCB, JEM, JGP",
  url: "https://rupress.org/jcb/pages/editorial-policies",
  verified: "July 2026"
},
{
  org: "ASM Journals",
  full: "American Society for Microbiology, mBio, mSystems, mSphere, Microbiology Spectrum and 13 further titles",
  cat: "journal",
  verdict: "Every manuscript with halftone images screened by Imagetwin at revision · disclosure required · most flagged issues turn out to be honest error.",
  chips: [{t:"Images: Imagetwin screened",s:"warn"},{t:"Writing: disclose",s:"ok"},{t:"Authorship: prohibited",s:"stop"}],
  writing: "Standard disclosure of generative AI use in manuscript preparation; AI cannot be an author.",
  images: "Since early 2023, Imagetwin has been part of routine ethics checks across all 17 ASM journal titles. Every manuscript containing halftone images, western blots, microscopy, immunofluorescence, photographs, is screened for duplication at the revision or resubmission stage, alongside text-similarity checks. Revised figures are re-screened to confirm concerns are resolved and no new duplications introduced, and the tool is also used to validate reader-flagged concerns post-publication. Line art, sketches and graphs are outside its detection range. Flags are verified by scientifically trained staff, including Photoshop difference-layer analysis, to filter false positives.",
  review: "Standard confidentiality expectations.",
  screening: "Imagetwin plus in-house expert verification. ASM's published one-year pilot found image duplications in 3.9% of accepted eligible manuscripts before publication; most were unintentional and readily resolved, and of 2,627 manuscripts screened, acceptance was revoked in six cases (0.23%).",
  forYou: "The ASM numbers are the best public evidence that most image flags are mistakes rather than misconduct, which is exactly why catching them before submission, rather than after publication, is worth the effort.",
  covers: "All 17 ASM journal titles",
  url: "https://journals.asm.org/journal/mbio",
  verified: "July 2026"
},
{
  org: "PLOS",
  full: "PLOS Biology · PLOS Medicine · PLOS ONE · PLOS Genetics and the PLOS portfolio",
  cat: "journal",
  verdict: "Report AI contributions in a dedicated Methods section · layered pre-publication screening that has pushed desk rejections from 13% to 40%.",
  chips: [{t:"Writing: dedicated section",s:"ok"},{t:"Authorship: prohibited",s:"stop"},{t:"Screening: layered",s:"warn"}],
  writing: "Contributions by AI tools to a study or an article's content must be clearly reported in a dedicated section of the Methods, or in the Acknowledgements for article types without a Methods section.",
  images: "Image analysis forms part of PLOS's pre-publication checks; data-availability requirements are among the strongest in the field.",
  review: "Confidentiality expectations apply to reviewers.",
  screening: "PLOS combines manual and technological screening, including AI tools, with all submissions passing a series of pre-publication checks. It participates in the STM Integrity Hub's cross-publisher duplicate-submission screening and in United2Act with COPE. Between 2021 and 2024, PLOS ONE detected 50 large-scale integrity 'megacases' involving more than 7,000 submissions and publications, spanning paper mills, authorship, peer review and policy compliance. Scaled screening pushed desk rejections from 13% in 2021 to 40% by 2025.",
  forYou: "A 40% desk-rejection rate at PLOS ONE means most rejections now happen before review. The compliance layer, data availability, disclosure, authorship, is as decisive as the science.",
  covers: "The PLOS journal portfolio",
  url: "https://journals.plos.org/plosone/s/ethical-publishing-practice",
  verified: "July 2026"
},
{
  org: "FEBS Press",
  full: "The FEBS Journal · FEBS Letters · FEBS Open Bio · Molecular Oncology",
  cat: "journal",
  verdict: "A dedicated generative-AI policy within a long-standing emphasis on data provenance and figure checking.",
  chips: [{t:"Writing: disclose",s:"ok"},{t:"Authorship: prohibited",s:"stop"},{t:"Figures: checked",s:"warn"}],
  writing: "The FEBS Press journals maintain an explicit 'Use of generative AI' section in their author guidelines, sitting alongside their policies on authorship and author contributions, data availability and transparent peer review. Use must be disclosed and cannot amount to authorship.",
  images: "FEBS has a long-standing emphasis on data provenance and figure checking; the 2026 opening editorial by Editor-in-Chief Seamus Martin addresses safeguarding scientific integrity amid the rise of generative AI in publishing.",
  review: "FEBS Press operates transparent peer review, with reviewer confidentiality obligations.",
  screening: "Figure and data integrity checking, on the Wiley platform with its associated screening infrastructure.",
  forYou: "A useful reference point if you want an integrity-forward society journal's stance stated in one place.",
  covers: "The four FEBS Press titles",
  url: "https://febs.onlinelibrary.wiley.com/hub/journal/17424658/journal-menu/author-guidelines",
  verified: "July 2026"
},
{
  org: "The Company of Biologists",
  full: "Development · Journal of Cell Science · Journal of Experimental Biology · Disease Models &amp; Mechanisms · Biology Open",
  cat: "journal",
  verdict: "Disclosure required with human accountability · figure-integrity checking consistent with life-science norms.",
  chips: [{t:"Writing: disclose",s:"ok"},{t:"Authorship: prohibited",s:"stop"},{t:"Figures: checked",s:"warn"}],
  writing: "The Company of Biologists journals follow COPE-aligned norms: AI cannot be an author, use in manuscript preparation must be disclosed, and authors are accountable for all content.",
  images: "Figure preparation and image-integrity expectations follow life-science community standards, with original data requested where questions arise.",
  review: "Standard confidentiality expectations for reviewers.",
  screening: "Similarity screening and figure checks as part of the editorial workflow.",
  forYou: "Common destinations for NCBS work, check the specific journal's author guidelines, as details differ slightly across the five titles.",
  covers: "Development, Journal of Cell Science, Journal of Experimental Biology, Disease Models &amp; Mechanisms, Biology Open",
  url: "https://www.biologists.com/journal-policies/",
  verified: "July 2026"
},
{
  org: "JAMA Network",
  full: "JAMA and the JAMA Network journals",
  cat: "journal",
  verdict: "Permitted with reporting of tool, version and use · no AI authors · reviewer use allowed only where confidentiality is assured.",
  chips: [{t:"Writing: disclose",s:"ok"},{t:"Authorship: prohibited",s:"stop"},{t:"Peer review: conditional",s:"warn"}],
  writing: "JAMA permits AI-assisted writing with reporting of the tool, its version, and how it was used; AI cannot be an author. JAMA sits at the more permissive end among medical journals while retaining full disclosure.",
  images: "AI-generated images fall within disclosure requirements; data-image integrity expectations follow ICMJE norms.",
  review: "Reviewers may use AI only in ways that preserve manuscript confidentiality, one of the few venues where reviewer use is conditionally permitted rather than banned outright.",
  screening: "Similarity and integrity screening in line with major medical publishers.",
  forYou: "Note the contrast with Nature, Science, Elsevier and The Lancet, all of which prohibit reviewer AI use entirely.",
  covers: "JAMA and the JAMA Network specialty journals",
  url: "https://jamanetwork.com/journals/jama/pages/instructions-for-authors",
  verified: "July 2026"
},
{
  org: "The Lancet",
  full: "The Lancet family (Elsevier)",
  cat: "journal",
  verdict: "Permitted with disclosure · no AI authorship · reviewers may not use AI on manuscripts.",
  chips: [{t:"Writing: disclose",s:"ok"},{t:"Authorship: prohibited",s:"stop"},{t:"Peer review: prohibited",s:"stop"}],
  writing: "AI-assisted writing is permitted with declaration, under Elsevier's framework plus The Lancet's own editorial guidance. AI cannot be an author.",
  images: "Elsevier's prohibition on AI-created or AI-altered images applies.",
  review: "Reviewers are not permitted to use AI in assessing manuscripts, on confidentiality grounds.",
  screening: "Elsevier's Check Integrity screening plus journal-level editorial checks.",
  forYou: "Follow the Elsevier dedicated-statement format for disclosure, placed before the references.",
  covers: "The Lancet and its specialty and regional titles",
  url: "https://www.thelancet.com/for-authors",
  verified: "July 2026"
},
{
  org: "BMJ",
  full: "BMJ and BMJ Group journals",
  cat: "journal",
  verdict: "Declare AI use in the contributorship statement · no AI authors · disclosure rates in practice remain strikingly low.",
  chips: [{t:"Writing: contributorship",s:"ok"},{t:"Authorship: prohibited",s:"stop"}],
  writing: "BMJ requires authors to declare AI use in producing submitted work, with accountability resting on the named authors, and does not accept AI tools as authors.",
  images: "Disclosure requirements extend to AI-generated visual content.",
  review: "Reviewer confidentiality expectations apply.",
  screening: "Standard similarity and integrity screening. A 2026 conference report found that only 5.7% of more than 25,000 submissions to 49 BMJ Publishing Group journals in 2024 contained AI disclosures, a concrete illustration of the transparency gap the PNAS study describes.",
  forYou: "Low disclosure rates across a field do not make non-disclosure acceptable; they make honest disclosure distinctive.",
  covers: "BMJ, BMJ Open, BMJ Global Health, BMJ Oncology and the BMJ specialty journals",
  url: "https://www.bmj.com/about-bmj/resources-authors",
  verified: "July 2026"
},
{
  org: "ACS Publications",
  full: "American Chemical Society journals",
  cat: "journal",
  verdict: "Declare AI use in manuscript preparation in the Acknowledgements · accountability rests entirely with human authors.",
  chips: [{t:"Writing: Acknowledgements",s:"ok"},{t:"Authorship: prohibited",s:"stop"}],
  writing: "ACS ethical guidelines require identification of AI tools used in preparing a submission, with human authors bearing full accountability. AI does not meet ACS authorship criteria.",
  images: "Figure integrity expectations follow chemistry community standards; AI-generated data images are not acceptable.",
  review: "Confidentiality expectations apply.",
  screening: "Similarity screening and figure checks within ACS editorial workflows.",
  forYou: "Acknowledgements is the disclosure location at ACS titles, not Methods.",
  covers: "The ACS journal portfolio including the ACS Au open-access series",
  url: "https://publish.acs.org/publish/author_guidelines",
  verified: "July 2026"
},
{
  org: "IEEE",
  full: "IEEE journals, conferences and periodicals",
  cat: "journal",
  verdict: "Disclose AI-generated text, figures, images <em>or code</em> in the Acknowledgements, and cite the AI system in the sections that use it.",
  chips: [{t:"Writing: disclose + cite",s:"ok"},{t:"Code: covered",s:"warn"},{t:"Authorship: prohibited",s:"stop"}],
  writing: "IEEE requires that AI-generated content of any kind, text, figures, images or code, be disclosed in the Acknowledgements of papers submitted to IEEE conferences and periodicals, with sections using AI-generated text carrying a citation to the AI system used.",
  images: "AI-generated figures and images fall explicitly within the disclosure requirement.",
  review: "IEEE has been noted as lacking explicit conference-reviewer AI policies, unlike ACM and AAAI, check the specific conference's call.",
  screening: "A partner in Wiley's Papermill Detection testing alongside SAGE.",
  forYou: "IEEE is one of the few bodies that names <em>code</em> explicitly. If a model wrote part of your implementation, that is disclosable here.",
  covers: "IEEE periodicals and conference proceedings",
  url: "https://journals.ieeeauthorcenter.ieee.org/become-an-ieee-journal-author/publishing-ethics/guidelines-and-policies/submission-and-peer-review-policies/",
  verified: "July 2026"
},
{
  org: "ACM",
  full: "Association for Computing Machinery",
  cat: "journal",
  verdict: "Generative AI content permitted with full disclosure in the work · AI may not be an author · reviewers may use AI without exposing submissions.",
  chips: [{t:"Writing: disclose",s:"ok"},{t:"Authorship: prohibited",s:"stop"},{t:"Peer review: conditional",s:"warn"}],
  writing: "ACM policy states that generative AI tools may not be listed as authors of an ACM published work; using such tools to create content is permitted but must be fully disclosed within the work.",
  images: "Generated figures fall within the disclosure requirement.",
  review: "ACM, along with AAAI, permits reviewers to use generative AI to enhance their reviews provided submissions themselves are never exposed to those systems. Individual conferences may impose stricter rules than the society policy.",
  screening: "Conference- and journal-level screening varies.",
  forYou: "In computing venues the society policy is the floor; the specific conference's call for papers may say something stricter.",
  covers: "ACM journals and conference proceedings",
  url: "https://www.acm.org/publications/policies/frequently-asked-questions",
  verified: "July 2026"
},
{
  org: "APA Publishing",
  full: "American Psychological Association journals",
  cat: "journal",
  verdict: "Disclose AI use in the Methods section <em>and cite the model</em> · AI cannot be named an author.",
  chips: [{t:"Writing: Methods + cite",s:"ok"},{t:"Authorship: prohibited",s:"stop"}],
  writing: "When a generative AI model is used in drafting a manuscript for an APA publication, the use must be disclosed in the Methods section and cited. AI cannot be named as an author.",
  images: "Disclosure requirements extend to generated visual material.",
  review: "Confidentiality expectations apply.",
  screening: "Standard similarity screening.",
  forYou: "APA is one of the venues that asks you to <em>cite</em> the model, not merely mention it, follow their citation format for software.",
  covers: "APA journals",
  url: "https://www.apa.org/pubs/journals/resources/publishing-policies",
  verified: "July 2026"
},

/* ================= PREPRINT SERVERS ================= */
{
  org: "bioRxiv",
  full: "bioRxiv preprint server · Cold Spring Harbor Laboratory",
  cat: "preprint",
  verdict: "Disclose AI use in the manuscript · AI cannot be an author · every submission is screened before posting.",
  chips: [{t:"Writing: disclose",s:"ok"},{t:"Authorship: prohibited",s:"stop"},{t:"Screening: all submissions",s:"warn"}],
  writing: "Authors are responsible for all content they submit, including material produced by generative AI and related technologies. Use of these tools should be detailed in the manuscript, and the output must not plagiarise other work or breach copyright. AI tools and large language models do not meet bioRxiv&rsquo;s authorship requirement and may not be listed as authors.",
  images: "Covered by the same responsibility principle: figures are the authors&rsquo; responsibility regardless of the tool that touched them.",
  review: "bioRxiv posts without peer review; screening stands in its place.",
  screening: "All submissions are screened before posting for plagiarism, non-scientific content, inappropriate article types, and material that could potentially endanger health.",
  forYou: "Most NCBS papers touch bioRxiv before a journal. The disclosure you will owe the journal is the same one bioRxiv expects, so write it once, at preprint time, and let it travel with the paper.",
  covers: "bioRxiv preprints; medRxiv operates equivalent requirements",
  url: "https://www.biorxiv.org/about/FAQ",
  verified: "August 2026"
},


/* ================= FUNDERS ================= */
{
  org: "ANRF · SERB",
  full: "Anusandhan National Research Foundation, incorporating the former Science and Engineering Research Board",
  cat: "funder",
  verdict: "No stated policy on generative AI in proposals · the plagiarism rules are explicit, and they already reach AI-drafted text.",
  chips: [{t:"Proposals: no AI policy yet",s:"warn"},{t:"Plagiarism: 5-year ban",s:"stop"}],
  writing: "Proposals must be original, and plagiarism in any form is unacceptable. Applicants are asked to pre-check proposals for plagiarism before uploading; any verbatim text must be quoted and cited; and every PI must declare that they have not been penalised on scientific-ethics or plagiarism charges in the past five years. Generative AI is not mentioned anywhere in the guidance, which means AI-drafted text is governed by the ordinary originality rules: if a model reproduces someone else&rsquo;s words or ideas into your proposal, that is plagiarism, whoever typed it.",
  images: "Not addressed.",
  review: "No public position on reviewer use of AI.",
  screening: "ANRF reserves the right to withdraw funding on confirmed ethics violations and to bar defaulters from applying for a minimum of five years, extendable with the severity of the case.",
  forYou: "Until ANRF publishes an AI rule, the safe reading is that TIFR&rsquo;s own guidelines govern your use, and the existing plagiarism machinery already applies to anything a model wrote. As of August 2026, no major Indian funding agency has published an explicit generative-AI policy for proposals.",
  covers: "ANRF schemes including the former SERB portfolio: Core Research Grant, Start-up Research Grant, MATRICS, national fellowships",
  url: "https://serb.gov.in/page/english/scientific_ethics_and_plagiarism",
  verified: "August 2026"
},
{
  org: "Wellcome · UK funders joint statement",
  full: "Wellcome, UKRI, Cancer Research UK, NIHR, British Heart Foundation, Royal Society and others · the reference point for DBT/Wellcome India Alliance applicants",
  cat: "funder",
  verdict: "Applicants may use generative AI if the outputs are acknowledged · reviewers may not put application content into AI tools at all.",
  chips: [{t:"Proposals: acknowledge",s:"ok"},{t:"Peer review: prohibited",s:"stop"}],
  writing: "A joint statement by eight major UK research funders (September 2023), including Wellcome and UKRI, permits responsible use of generative AI in funding applications on the condition that any outputs from such tools are acknowledged, with individual funders free to add stricter scheme-level rules of their own.",
  images: "Not separately addressed.",
  review: "Categorical: peer reviewers must not input content from confidential funding applications or reviews into generative AI tools, nor use such tools to develop their critiques, on confidentiality and expertise grounds.",
  screening: "Compliance runs through each funder&rsquo;s own assurance processes.",
  forYou: "The India Alliance (DBT/Wellcome) has published no AI policy of its own as of August 2026, so Wellcome&rsquo;s standard is the sensible reference for its fellows and applicants: acknowledge AI use in an application, and if you review for any funder, keep the application out of every AI tool.",
  covers: "Wellcome and UK funder applications; the practical reference for DBT/Wellcome India Alliance fellowships",
  url: "https://wellcome.org/about-us/positions-and-statements/joint-statement-generative-ai",
  verified: "August 2026"
},
{
  org: "ICMR",
  full: "Indian Council of Medical Research",
  cat: "funder",
  verdict: "The 2023 guidelines govern AI as a technology in health research, ethics review, consent, validation · they say nothing about AI as a writing aid.",
  chips: [{t:"AI in research: ethics review",s:"warn"},{t:"Manuscript writing: not covered",s:"warn"}],
  writing: "The Ethical Guidelines for Application of Artificial Intelligence in Biomedical Research and Healthcare (2023) concern AI as a research technology, not as a drafting tool. They set out ethics-review expectations, informed-consent processes, validation and governance frameworks for AI-based tools applied to biomedical and health data, addressed to developers, researchers, clinicians and ethics committees. The use of generative AI in writing manuscripts or proposals is not addressed.",
  images: "Not addressed.",
  review: "Not addressed.",
  screening: "Compliance runs through institutional ethics committees for ICMR-funded and health-related research.",
  forYou: "Read these if your project builds or applies AI on patient or biomedical data, because they shape what your ethics application must contain. For LLMs as writing aids they are silent; your target journal&rsquo;s policy and TIFR&rsquo;s guidelines govern that.",
  covers: "ICMR-funded biomedical and health research involving AI technologies",
  url: "https://www.icmr.gov.in/ethical-guidelines-for-application-of-artificial-intelligence-in-biomedical-research-and-healthcare",
  verified: "August 2026"
},
{
  org: "NIH",
  full: "U.S. National Institutes of Health",
  cat: "funder",
  verdict: "Generative AI is prohibited outright in NIH peer review, uploading application content breaches confidentiality.",
  chips: [{t:"Peer review: prohibited",s:"stop"}],
  writing: "NIH's restriction targets the review process rather than authorship of publications.",
  images: "Not addressed by this notice.",
  review: "Notice NOT-OD-23-149 (June 2023) bars reviewers from using natural-language processors, large language models or other generative AI to analyse or critique grant applications and contract proposals, on the grounds that uploading their content to online tools violates the confidentiality reviewers agree to.",
  screening: "NIH-funded work remains subject to the ORI framework on research misconduct, fabrication, falsification, plagiarism.",
  forYou: "If you review for NIH, the rule is absolute: nothing from an application goes into any AI tool.",
  covers: "NIH peer review and contract proposal review",
  url: "https://grants.nih.gov/grants/guide/notice-files/NOT-OD-23-149.html",
  verified: "July 2026"
},
{
  org: "NSF",
  full: "U.S. National Science Foundation",
  cat: "funder",
  verdict: "Reviewers may not upload proposal content to non-approved AI · proposers are asked to indicate generative AI use.",
  chips: [{t:"Peer review: prohibited",s:"stop"},{t:"Proposals: disclose",s:"ok"}],
  writing: "NSF encourages proposers to indicate in the project description whether and how generative AI was used in developing the proposal.",
  images: "Not separately addressed.",
  review: "Reviewers are prohibited from uploading proposal content to unapproved generative AI tools, on confidentiality grounds.",
  screening: "Merit review integrity is handled through NSF's own processes.",
  forYou: "Relevant if you review for or apply to NSF, and a useful template for how funders are likely to move generally.",
  covers: "NSF merit review",
  url: "https://www.nsf.gov/news/notice-to-the-research-community-on-ai",
  verified: "July 2026"
}
];
